
services:
###> doctrine/doctrine-bundle ###
  database:
    image: mariadb:${MARIADB_VERSION:-10.11}
    environment:
      MARIADB_DATABASE: ${MARIADB_DATABASE:-vape}
      MARIADB_USER: ${MARIADB_USER:-app}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD:-app}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD:-root}
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "${MARIADB_USER:-app}", "--password=${MARIADB_PASSWORD:-app}"]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - database_data:/var/lib/mysql:rw
###< doctrine/doctrine-bundle ###

volumes:
###> doctrine/doctrine-bundle ###
  database_data:
###< doctrine/doctrine-bundle ###
